branches:
  only:
    - 'master'

language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - BRANCHES=1.6/master
  - BRANCHES=1.5/master
  - BRANCHES=1.4/master

before_install:
  - git clone --recursive --quiet --branch=$BRANCHES git://github.com/fuel/fuel.git "$HOME/fuelphp"

install:
  - if [ $BRANCHES = "1.6/master" ]; then pushd "$HOME/fuelphp" ; wget http://getcomposer.org/composer.phar ; php composer.phar install; popd ; fi

before_script:
  - ln -sf "`pwd`" "$HOME/fuelphp/fuel/packages/ouisearch"
  - cp -f "`pwd`/tests/travis-ci/config.php"  "$HOME/fuelphp/fuel/app/config/"
  - cp -f "`pwd`/tests/travis-ci/test/db.php" "$HOME/fuelphp/fuel/app/config/test/"
  - mysql -e 'create database fuel_test;'

script:
  - phpunit -c "$HOME/fuelphp/fuel/core/phpunit.xml" --group=OuiSearchPackage --coverage-text

